# Generated by Django 4.2.7 on 2023-12-28 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100)),
                ('book_price', models.IntegerField()),
                ('book_image', models.ImageField(upload_to='books/media/uploads/')),
                ('book_description', models.TextField()),
                ('book_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.bookcategorymodel')),
            ],
        ),
    ]
