# Generated by Django 4.2.7 on 2023-12-30 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookreviewmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreviewmodel',
            name='rating',
        ),
    ]
