# Generated by Django 4.2.7 on 2023-12-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_bookreviewmodel_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookReviewModel',
        ),
    ]
